---
output:
  html_document: default
  pdf_document: default
---
```{r eval=FALSE, include=FALSE}
install.packages("rgbif")
```
```{r}
library(rgbif)
```



# Counting occurence records
```{r}
# occurence counts of GBIF data (all)
# Type of observations.
occ_count()
occ_count(basisOfRecord='OBSERVATION')
occ_count(basisOfRecord='HUMAN_OBSERVATION')
occ_count(basisOfRecord='MACHINE_OBSERVATION')
occ_count(basisOfRecord='LITERATURE')
occ_count(basisOfRecord='LIVING_SPECIMEN')
occ_count(basisOfRecord='FOSSIL_SPECIMEN')
```

```{r}
occ_count(georeferenced = TRUE)
```

Records for Ragweed.
```{r}
# Ragweed (Genus:Ambrosia) is 3110576.
occ_count(taxonKey=3110576)
```

All records from 2012
```{r}
occ_count(year = 2012)
```

```{r}
# Ragweed (Genus:Ambrosia, taxonKey= 3110576).
# By human observation
# In United States (country code = US)
# Has long/lat data
occ_count(basisOfRecord='HUMAN_OBSERVATION', country = "US", taxonKey=3110588, georeferenced = TRUE)
```

acceptable set
```
• basisOfRecord, country
• basisOfRecord, country, isGeoreferenced
• basisOfRecord, country, isGeoreferenced, taxonKey
• basisOfRecord, country, taxonKey
• basisOfRecord, datasetKey
• basisOfRecord, datasetKey, isGeoreferenced
• basisOfRecord, datasetKey, isGeoreferenced, taxonKey
• basisOfRecord, datasetKey, taxonKey
• basisOfRecord, isGeoreferenced, taxonKey
• basisOfRecord, isGeoreferenced, publishingCountry
• basisOfRecord, isGeoreferenced, publishingCountry, taxonKey
• basisOfRecord, publishingCountry
• basisOfRecord, publishingCountry, taxonKey
• basisOfRecord, taxonKey
• country
• country, datasetKey, isGeoreferenced
• country, isGeoreferenced
• country, isGeoreferenced, publishingCountry
• country, isGeoreferenced, taxonKey
• country, publishingCountry
• country, taxonKey
• country, typeStatus
• datasetKey
• datasetKey, isGeoreferenced
• datasetKey, isGeoreferenced, taxonKey
• datasetKey, issue
• datasetKey, taxonKey
• datasetKey, typeStatus
• isGeoreferenced
• isGeoreferenced, publishingCountry
• isGeoreferenced, publishingCountry, taxonKey
• isGeoreferenced, taxonKey
• issue
• publishingCountry
• publishingCountry, taxonKey
• publishingCountry, typeStatus
• taxonKey
• taxonKey, typeStatus
• typeStatus
• protocol
• year
```



# how to get taxon key.
Why is the usageKey and taxonKey are different? === synonim problem!!
```{r}
name_backbone(name='Ambrosia', rank = "genus")$genusKey
name_backbone(name='Ambrosia aptera', rank = "species")$speciesKey
```

# How to get country code
```{r}
# Country codes are stored in isocodes.csv.
head(isocodes)
```

E.g. occurence records of ragweed in USA.
```{r}
key <- name_backbone(name = 'Ambrosia aptera', rank = "species")$speciesKey
usa_code <- isocodes[grep("^United States$", isocodes$name), "code"]
occ_count(basisOfRecord = 'HUMAN_OBSERVATION', taxonKey = key, country = usa_code, georeferenced = TRUE)
```

-------------------------------------------------------------------------
# If you seach for infomation about specific taxon.
```{r}
spdata <- name_lookup(query="Ambrosia", rank="genus", return="data")
head(spdata)
```
```{r}
res <- name_lookup(query='canada', hl=TRUE, limit=5)
gbif_names(res)
```





```
taxonkey <- spdata[1, "nubKey"]
taxonkey
```

```{r}
spdata2 <- name_usage(name = "Ambrosia", rank = "genus", return = "data")
head(spdata2)
```

If you are unsure about taxonomic names and their keys.
```{r}
name_suggest(q='Plasmodium', rank = "genus")
```
```{r}
name_suggest(q='Ambrosia')
```


```{r}
spbkbn <- name_backbone(name='Ambrosia', kingdom='plants')
spbkbn
```

If you are unsure about what kind of taxonomic rank can be used.
```{r}
taxrank()
```


Data for a single occurence. Requires occurrence key!
```
occ_get(key=3110588, return='data')
```

Search for occurence data in sp level. 
Note that hasCoordinate in occ_search() is the same as georeferenced in occ_count()
```{r}
key <- name_backbone(name='Ambrosia aptera')$speciesKey
spdat <- occ_search(taxonKey=key, return='data', limit=300)
```
Search for occurence data of all species in the specified genus. 
```{r}
gendat <- occ_search(taxonKey=3110576, return='data', limit=300)
```


country&taxonkey
```{r}
key <- name_backbone(name='Ambrosia aptera')$speciesKey
usa_code <- isocodes[grep("^United States$", isocodes$name), "code"]
gendat <- occ_search(taxonKey=key, country=usa_code, return='data', limit=300)
```


Plot on map
```
library(ggplot2)
#use mapr package?
ggplot(dat)
```

----------------------------------------------------------------------------------
```{r}
# Example: Malaria parasite, Genus Plasmodium.
occ_malaria <- occ_search(taxonKey=8364053, return='data')
library(ggplot2)
library(maps)
world <- map_data("world")
ggplot(world, aes(long, lat)) +
geom_polygon(aes(group = group), fill = "white", 
              color = "gray40", size = .3) +
geom_jitter(data = occ_malaria,
aes(decimalLongitude, decimalLatitude), alpha=0.6, 
             size = 3, color = "red")
```

mapping experiment
```{r}
x <- map_fetch(taxonKey = 3110576, y = 0, srs = "EPSG:3857")
plot(x)
```


```{r}
## Not run:
if (
requireNamespace("png", quietly = TRUE) &&
requireNamespace("raster", quietly = TRUE)
) {
x <- map_fetch(taxonKey = 3110576)
x
# gives a RasterLayer object
class(x)
# visualize
library(raster)
plot(x)
# different srs
## 3857
y <- map_fetch(taxonKey = 3110576, srs = "EPSG:3857")
plot(y)
## 3031
z <- map_fetch(taxonKey = 3110576, srs = "EPSG:3031", verbose = TRUE)
plot(z)
# 3575
z <- map_fetch(taxonKey = 3110576, srs = "EPSG:3575")
plot(z)
# bin
plot(map_fetch(taxonKey = 3110576, bin = "hex",
hexPerTile = 30, style = "classic-noborder.poly"))
# styles
plot(map_fetch(taxonKey = 3110576, style = "purpleYellow.point"))
# query with basisOfRecord
map_fetch(taxonKey = 3110576, basisOfRecord = "HUMAN_OBSERVATION")
map_fetch(taxonKey = 3110576, basisOfRecord = c("HUMAN_OBSERVATION", "LIVING_SPECIMEN"))
}
## End(Not run)
```






-----------------------------------------------------------------------------------
name_suggest() is optimized for speed, and gives back suggested names based on query parameters.```{r}
head(name_suggest(q='Puma concolor'))
```

-------------------------------------------------------------------------

single occurence
```{r}
occ_get(key=240713150, return='data')
```

```{r}
occ_get(key=240713150, return='hier')
```

```{r}
occ_get(key=240713150, return='all')
```

multiple occurences
```{r}
occ_get(key=c(101010, 240713150, 855998194), return='data')
```

search for specific taxa
```{r}
occ_search(scientificName = "Ursus americanus", limit = 20)
```

```{r}
key <- name_backbone(name='Puma concolor')$speciesKey
dat <- occ_search(taxonKey=key, return='data', limit=300)
```
```{r}
library(ggplot2)
#use mapr package?
mapr(dat)
```








???what's datasetkey???
```{r}
occ_count(datasetKey='9e7ea106-0bf8-4087-bb61-dfe4f29e0f17')
```